install:
  - git clone https://github.com/nsherry4/Libraries.git /tmp/libraries
  - cd /tmp/libraries && mvn install
  - cd -

cache:
  directories:
    - /home/travis/.m2/repository/org/codehaus
    - /home/travis/.m2/repository/org/apache
    - /home/travis/.m2/repository/com/google
    - /home/travis/.m2/repository/org/jfxtras

language: java
sudo: false
script: mvn clean verify

